# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nlp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nlp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tnlp.proto\x12\x03nlp\".\n\x10SentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\"1\n\x11SentimentResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x32O\n\nNLPManager\x12\x41\n\x10\x41nalyzeSentiment\x12\x15.nlp.SentimentRequest\x1a\x16.nlp.SentimentResponseB\x18Z\x16github.com/zen-nlp/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026github.com/zen-nlp/api'
  _globals['_SENTIMENTREQUEST']._serialized_start=18
  _globals['_SENTIMENTREQUEST']._serialized_end=64
  _globals['_SENTIMENTRESPONSE']._serialized_start=66
  _globals['_SENTIMENTRESPONSE']._serialized_end=115
  _globals['_NLPMANAGER']._serialized_start=117
  _globals['_NLPMANAGER']._serialized_end=196
# @@protoc_insertion_point(module_scope)
