// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/nlp.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SentimentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentimentRequest) Reset() {
	*x = SentimentRequest{}
	mi := &file_api_nlp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentimentRequest) ProtoMessage() {}

func (x *SentimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nlp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentimentRequest.ProtoReflect.Descriptor instead.
func (*SentimentRequest) Descriptor() ([]byte, []int) {
	return file_api_nlp_proto_rawDescGZIP(), []int{0}
}

func (x *SentimentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SentimentRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type SentimentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentimentResponse) Reset() {
	*x = SentimentResponse{}
	mi := &file_api_nlp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentimentResponse) ProtoMessage() {}

func (x *SentimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_nlp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentimentResponse.ProtoReflect.Descriptor instead.
func (*SentimentResponse) Descriptor() ([]byte, []int) {
	return file_api_nlp_proto_rawDescGZIP(), []int{1}
}

func (x *SentimentResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SentimentResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_api_nlp_proto protoreflect.FileDescriptor

const file_api_nlp_proto_rawDesc = "" +
	"\n" +
	"\rapi/nlp.proto\x12\x03nlp\":\n" +
	"\x10SentimentRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"?\n" +
	"\x11SentimentResponse\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score2O\n" +
	"\n" +
	"NLPManager\x12A\n" +
	"\x10AnalyzeSentiment\x12\x15.nlp.SentimentRequest\x1a\x16.nlp.SentimentResponseB)Z'github.com/Mannymz/ZenNLP/apib\x06proto3"

var (
	file_api_nlp_proto_rawDescOnce sync.Once
	file_api_nlp_proto_rawDescData []byte
)

func file_api_nlp_proto_rawDescGZIP() []byte {
	file_api_nlp_proto_rawDescOnce.Do(func() {
		file_api_nlp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_nlp_proto_rawDesc), len(file_api_nlp_proto_rawDesc)))
	})
	return file_api_nlp_proto_rawDescData
}

var file_api_nlp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_nlp_proto_goTypes = []any{
	(*SentimentRequest)(nil),  // 0: nlp.SentimentRequest
	(*SentimentResponse)(nil), // 1: nlp.SentimentResponse
}
var file_api_nlp_proto_depIdxs = []int32{
	0, // 0: nlp.NLPManager.AnalyzeSentiment:input_type -> nlp.SentimentRequest
	1, // 1: nlp.NLPManager.AnalyzeSentiment:output_type -> nlp.SentimentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_nlp_proto_init() }
func file_api_nlp_proto_init() {
	if File_api_nlp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_nlp_proto_rawDesc), len(file_api_nlp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_nlp_proto_goTypes,
		DependencyIndexes: file_api_nlp_proto_depIdxs,
		MessageInfos:      file_api_nlp_proto_msgTypes,
	}.Build()
	File_api_nlp_proto = out.File
	file_api_nlp_proto_goTypes = nil
	file_api_nlp_proto_depIdxs = nil
}
