// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: api/nlp.proto

package api

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SentimentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Lang string `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
}

func (x *SentimentRequest) Reset() {
	*x = SentimentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nlp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SentimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentimentRequest) ProtoMessage() {}

func (x *SentimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nlp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentimentRequest.ProtoReflect.Descriptor instead.
func (*SentimentRequest) Descriptor() ([]byte, []int) {
	return file_api_nlp_proto_rawDescGZIP(), []int{0}
}

func (x *SentimentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SentimentRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type SentimentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string  `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Score float64 `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *SentimentResponse) Reset() {
	*x = SentimentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nlp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SentimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentimentResponse) ProtoMessage() {}

func (x *SentimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_nlp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentimentResponse.ProtoReflect.Descriptor instead.
func (*SentimentResponse) Descriptor() ([]byte, []int) {
	return file_api_nlp_proto_rawDescGZIP(), []int{1}
}

func (x *SentimentResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SentimentResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_api_nlp_proto protoreflect.FileDescriptor

var file_api_nlp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6c, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6e, 0x6c, 0x70, 0x22, 0x3e, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67,
	0x22, 0x44, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x32, 0x5e, 0x0a, 0x0a, 0x4e, 0x4c, 0x50, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12,
	0x50, 0x0a, 0x10, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x53, 0x65, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x6e, 0x6c, 0x70, 0x2e, 0x53, 0x65, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6e, 0x6c, 0x70,
	0x2e, 0x53, 0x65, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x7a, 0x65, 0x6e, 0x2d, 0x6e, 0x6c, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_nlp_proto_rawDescOnce sync.Once
	file_api_nlp_proto_rawDescData = file_api_nlp_proto_rawDesc
)

func file_api_nlp_proto_rawDescGZIP() []byte {
	file_api_nlp_proto_rawDescOnce.Do(func() {
		file_api_nlp_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_nlp_proto_rawDescData)
	})
	return file_api_nlp_proto_rawDescData
}

var file_api_nlp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_nlp_proto_goTypes = []interface{}{
	(*SentimentRequest)(nil),  // 0: nlp.SentimentRequest
	(*SentimentResponse)(nil), // 1: nlp.SentimentResponse
}
var file_api_nlp_proto_depIdxs = []int32{
	0, // 0: nlp.NLPManager.AnalyzeSentiment:input_type -> nlp.SentimentRequest
	1, // 1: nlp.NLPManager.AnalyzeSentiment:output_type -> nlp.SentimentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_nlp_proto_init() }
func file_api_nlp_proto_init() {
	if File_api_nlp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_nlp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(type) {
			case *SentimentRequest:
				return v
			default:
				return nil
			}
		}
		file_api_nlp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(type) {
			case *SentimentResponse:
				return v
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_nlp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_nlp_proto_goTypes,
		DependencyIndexes: file_api_nlp_proto_depIdxs,
		MessageInfos:      file_api_nlp_proto_msgTypes,
	}.Build()
	File_api_nlp_proto = out.File
	file_api_nlp_proto_rawDesc = nil
	file_api_nlp_proto_goTypes = nil
	file_api_nlp_proto_depIdxs = nil
}
