// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: api/nlp.proto

package api

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NLPManager_AnalyzeSentiment_FullMethodName = "/nlp.NLPManager/AnalyzeSentiment"
)

// NLPManagerClient is the client API for NLPManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NLPManagerClient interface {
	AnalyzeSentiment(ctx context.Context, in *SentimentRequest, opts ...grpc.CallOption) (*SentimentResponse, error)
}

type nLPManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewNLPManagerClient(cc grpc.ClientConnInterface) NLPManagerClient {
	return &nLPManagerClient{cc}
}

func (c *nLPManagerClient) AnalyzeSentiment(ctx context.Context, in *SentimentRequest, opts ...grpc.CallOption) (*SentimentResponse, error) {
	cOpts := append([]grpc.CallOption{}, opts...)
	out := new(SentimentResponse)
	err := c.cc.Invoke(ctx, NLPManager_AnalyzeSentiment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NLPManagerServer is the server API for NLPManager service.
// All implementations must embed UnimplementedNLPManagerServer
// for forward compatibility
type NLPManagerServer interface {
	AnalyzeSentiment(context.Context, *SentimentRequest) (*SentimentResponse, error)
	mustEmbedUnimplementedNLPManagerServer()
}

// UnimplementedNLPManagerServer must be embedded to have forward compatible implementations.
type UnimplementedNLPManagerServer struct {
}

func (UnimplementedNLPManagerServer) AnalyzeSentiment(context.Context, *SentimentRequest) (*SentimentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeSentiment not implemented")
}
func (UnimplementedNLPManagerServer) mustEmbedUnimplementedNLPManagerServer() {}

// UnsafeNLPManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NLPManagerServer will
// result in compilation errors.
type UnsafeNLPManagerServer interface {
	mustEmbedUnimplementedNLPManagerServer()
}

func RegisterNLPManagerServer(s grpc.ServiceRegistrar, srv NLPManagerServer) {
	s.RegisterService(&NLPManager_ServiceDesc, srv)
}

func _NLPManager_AnalyzeSentiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SentimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLPManagerServer).AnalyzeSentiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLPManager_AnalyzeSentiment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLPManagerServer).AnalyzeSentiment(ctx, req.(*SentimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NLPManager_ServiceDesc is the grpc.ServiceDesc for NLPManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NLPManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nlp.NLPManager",
	HandlerType: (*NLPManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeSentiment",
			Handler:    _NLPManager_AnalyzeSentiment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/nlp.proto",
}
